"""Initial Table Setup

Revision ID: 78871d27424f
Revises:
Create Date: 2022-03-22 20:03:38.256681

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "78871d27424f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("directory", sa.String(length=400), nullable=True),
        sa.Column(
            "date", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "classifier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model", sa.LargeBinary(), nullable=True),
        sa.Column(
            "date", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "email",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=True),
        sa.Column(
            "date", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("area", sa.Integer(), nullable=True),
        sa.Column("definition", sa.JSON(), nullable=True),
        sa.Column("type", sa.String(length=30), nullable=True),
        sa.Column(
            "date", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image", sa.LargeBinary(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "date", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column(
            "date", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("predictions")
    op.drop_table("fences")
    op.drop_table("email")
    op.drop_table("classifier")
    op.drop_table("areas")
    # ### end Alembic commands ###
