version: '3.1'

services:
  backend:
    image: stranger_danger:${TAG:-test}
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      target: ${TARGET:-backend}
    ports:
      - '8000:8000'
    volumes:
      - type: bind
        source: $DIRECTORY_TO_WATCH
        target: /tmp/stranger_danger
    env_file: .compose.env
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file: .compose.env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
    ports:
      - '5432:5432'
