version: '3.1'

services:
  backend:
    image: stranger_danger:1.0.0
    build:
      context: ./stranger_danger
      target: backend
    ports:
      - '8000:8000'
    env_file: .env
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_DATABASE
    ports:
      - '5432:5432'
