name: tests
on: push

env:
  SENDER: StrangerDanger
  EMAIL_PASSWORD: StrangerDanger
  EMAIL_SERVER: StrangerDanger
  EMAIL_PORT: 587
  EMAIL_SUBJECT: TestMail
  EMAIL_RECEIVER: valid@email-address.de
  DB_USER: StrangerDanger
  DB_PASSWORD: StrangerDanger
  DB_HOST: StrangerDanger
  DB_DATABASE: StrangerDanger
  DIRECTORY_TO_WATCH: StrangerDanger
  SECRET: Stanger

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.12]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run coverage run -m pytest tests
      - name: Coverage Report
        run: poetry run coverage report -m --skip-covered --ignore-errors
