name: tests
on: push

env:
  SENDER: StrangerDanger
  EMAIL_PASSWORD: StrangerDanger
  EMAIL_SERVER: StrangerDanger
  EMAIL_PORT: 587
  EMAIL_SUBJECT: TestMail
  EMAIL_RECEIVER: valid@email-address.de
  DB_USER: StrangerDanger
  DB_PASSWORD: StrangerDanger
  DB_HOST: StrangerDanger
  DB_DATABASE: StrangerDanger
  DIRECTORY_TO_WATCH: StrangerDanger
  SECRET: Stanger

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }V}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build test image
        run: docker-compose build test
      - name: Run tests in image
        run: docker-compose run make test
