name: tests
on: push
env:
  DB_USER: StrangerDanger
  DB_PASSWORD: StrangerDanger
  DB_HOST: StrangerDanger
  DB_DATABASE: StrangerDanger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SENDER: StrangerDanger
          envkey_EMAIL_PASSWORD: StrangerDanger
          envkey_EMAIL_SERVER: StrangerDanger
          envkey_EMAIL_PORT: 587
          envkey_EMAIL_SUBJECT: TestMail
          envkey_EMAIL_RECEIVER: valid@email-address.de
          envkey_DB_USER: StrangerDanger
          envkey_DB_PASSWORD: StrangerDanger
          envkey_DB_HOST: StrangerDanger
          envkey_DB_DATABASE: StrangerDanger
          envkey_DIRECTORY_TO_WATCH: StrangerDanger
          envkey_SECRET: Stanger
          file_name: .compose.env
      - name: Build test image
        run: docker-compose build test
      - name: Up Database
        run: docker-compose up -d db
      - name: Run tests in image
        run: docker-compose run test make test
